require './models/adjective.rb'

Adjective.create(letter: "A", adjective: "Timid")
Adjective.create(letter: "B", adjective: "Low-Energy")
Adjective.create(letter: "C", adjective: "Lying")
Adjective.create(letter: "D", adjective: "Weak")
Adjective.create(letter: "E", adjective: "Boring")
Adjective.create(letter: "F", adjective: "Overrated")
Adjective.create(letter: "G", adjective: "Jealous")
Adjective.create(letter: "H", adjective: "Moody")
Adjective.create(letter: "I", adjective: "Repulsive")
Adjective.create(letter: "J", adjective: "Yucky")
Adjective.create(letter: "K", adjective: "Unreliable")
Adjective.create(letter: "L", adjective: "Silly")
Adjective.create(letter: "M", adjective: "Fussy")
Adjective.create(letter: "N", adjective: "Ugly")
Adjective.create(letter: "O", adjective: "Hideous")
Adjective.create(letter: "P", adjective: "Dirty")
Adjective.create(letter: "Q", adjective: "Moron")
Adjective.create(letter: "R", adjective: "Little")
Adjective.create(letter: "S", adjective: "Crazy")
Adjective.create(letter: "T", adjective: "Cowardly")
Adjective.create(letter: "U", adjective: "Vain")
Adjective.create(letter: "V", adjective: "Clown")
Adjective.create(letter: "W", adjective: "Goofy")
Adjective.create(letter: "X", adjective: "Slob")
Adjective.create(letter: "Y", adjective: "Tiny")
Adjective.create(letter: "Z", adjective: "Flaccid")
